### ISSUE TITLE
Gherkin 4.0.0 causes yard-cucumber to downgrade to 2.2.3

### ISSUE THREAD

**Issue by tk8817** [burtlo/yard-cucumber#75]
I noticed when Cucumber upgraded to 2.4.0 which included Gherkin 4.0.0, bundler downgraded yard-cucumber to 2.2.3 from 3.0.0. This appears to be unwanted/unexpected behavior due to a poorly formed gherkin gemspec dependency in version 2.2.3. 

Ideally yard-cucumber should NOT claim compatibility and bundler should force cucumber back to the previous version which works. 

As an aside, I am going to fork the repo and bump the gherkin version to see what breaks. Overall we want to keep moving forward rather than locking in an old version of cucumber.

**Comment by vikramvi** [comment]
@tk8817 I'm trying to use this project but blocked because of https://github.com/burtlo/yard-cucumber/issues/80 , I think it's related to mismatch in version of gems I'm using. I'm trying to use all latest gems.

Can you please share your Gemfile and Gemfile.lock ?

Thanks in advance

Kind Regards,
Vikram
